#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_get google-android-installers/mirror

case "$1" in
    configure)
        if [ "${DEBCONF_RECONFIGURE}" = "1" ]; then
            db_fset google-android-installers/mirror seen false
            db_input high google-android-installers/mirror || true
            db_go || true
        else
            install -d -m0700 -o nobody -g nogroup /var/cache/google-android-m2repository-installer
            cp /usr/share/google-android-m2repository-installer/Makefile \
                /usr/share/google-android-m2repository-installer/android_m2repository_r35.zip.sha1 \
                /var/cache/google-android-m2repository-installer/
            make -C /var/cache/google-android-m2repository-installer/ DL_MIRROR="$RET" install
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
